"""Regenerate the checked-in Markdown reference for the Band CLI."""

from __future__ import annotations

import argparse
from pathlib import Path

from band_wezterm.cli import create_app

OUTPUT_PATH = Path(__file__).with_name("cli.md")


async def _async_noop(*_args: object, **_kwargs: object) -> int:
    return 0


def _noop(*_args: object, **_kwargs: object) -> int:
    return 0


def render() -> str:
    """Render the public command contract from its actual Cyclopts app."""
    app = create_app(
        setup=_noop,
        room_view=_noop,
        agent_view=_noop,
        create_agent=_noop,
        configure_agent=_noop,
        rooms=_async_noop,
        agents=_async_noop,
        create_room=_async_noop,
        delete_room=_async_noop,
        delete_agent=_async_noop,
        start_agent=_async_noop,
        stop_agent=_async_noop,
        agent_status=_async_noop,
        status=_async_noop,
    )
    return "<!-- Generated by docs/generate_cli_docs.py; do not edit. -->\n\n" + app.generate_docs()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.stdout:
        print(rendered, end="")
        return 0
    if args.check:
        if OUTPUT_PATH.read_text(encoding="utf-8") != rendered:
            print("docs/cli.md is stale; run `just cli-docs`.")
            return 1
        return 0
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
